[package]
name = "yew-query"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.57"
futures = "0.3.23"
type-map = "0.5.0"
wasm-bindgen-futures = "0.4.32"
yew = "0.19.3"
